"""
Email Sender Service

Sends report PDFs via email.
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

# Email configuration
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_EMAIL = os.getenv("FROM_EMAIL", SMTP_USER)
FROM_NAME = os.getenv("FROM_NAME", "MentorAI - CA Academy")


def send_email_report(
    to_email: str,
    student_name: str,
    pdf_path: str,
    solution_text: Optional[str] = None
) -> bool:
    """
    Send progress report via email.
    
    Returns True if sent successfully, False otherwise.
    """
    
    if not SMTP_USER or not SMTP_PASSWORD:
        print("[MentorAI] Email not configured (SMTP_USER/SMTP_PASSWORD not set)", flush=True)
        return False
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg["From"] = f"{FROM_NAME} <{FROM_EMAIL}>"
        msg["To"] = to_email
        msg["Subject"] = f"Your Weekly Progress Report - {student_name}"
        
        # Email body
        body = f"""Dear {student_name},

Please find attached your personalized weekly progress report.

This report includes:
• Your recent exam performance analysis
• Areas we discussed for improvement
• Personalized recommendations
• Action items for this week

Take some time to review the recommendations and implement them this week. Remember, consistency is key to success in CA exams!

If you have any questions, feel free to reply to this email or contact us during your next session.

Best wishes,
Your Mentor

---
This report was generated by MentorAI
"""
        
        msg.attach(MIMEText(body, "plain"))
        
        # Attach PDF/report file
        if pdf_path and os.path.exists(pdf_path):
            with open(pdf_path, "rb") as f:
                attachment = MIMEBase("application", "octet-stream")
                attachment.set_payload(f.read())
                encoders.encode_base64(attachment)
                
                filename = os.path.basename(pdf_path)
                attachment.add_header(
                    "Content-Disposition",
                    f"attachment; filename={filename}"
                )
                msg.attach(attachment)
        
        # Send email
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
        
        print(f"[MentorAI] Email sent to {to_email}", flush=True)
        return True
        
    except Exception as e:
        print(f"[MentorAI] Email send failed: {e}", flush=True)
        return False


def test_email_config() -> dict:
    """Test if email is configured correctly."""
    return {
        "configured": bool(SMTP_USER and SMTP_PASSWORD),
        "smtp_host": SMTP_HOST,
        "smtp_port": SMTP_PORT,
        "from_email": FROM_EMAIL
    }
